### ISSUE TITLE
大佬好 请教一下 这个项目使用openai api 可以修改其baseurl吗 

### ISSUE THREAD

**Issue by Savoir007** [DDizzzy79/Ret2GPT#13]
大佬 项目很牛逼 
闲了 向您请教一下 可以使用自定义openai 的baseurl吗‘’
因为官网地址个人接口老出现问题，我使用的是企业版的
所以接口地址不一样 可以通过修改代码进行 自定义baseurl

**Comment by shangsu** [comment]
我也有这个想法

**Comment by retr0reg** [comment]
可以的 稍后回家我去写一下 或者你可以开一个pr我来merge一下:)

**Comment by Savoir007** [comment]
langchain 真心没看懂咋搞 自己手动改过 但是没那个水平



在 2024-06-06 19:36:05，"Patrick Peng" ***@***.***> 写道：

可以的 稍后回家我去写一下 或者你可以开一个pr我来merge一下:)

**Comment by Savoir007** [comment]
因为chatopai 现在在国外非常麻烦 大佬有没有可能改成最近deepseek 这个模型的api
极快 deepseek 他的模型编程能力已经很强了
大佬 闲了指点一下langchain 我想研究一下



在 2024-06-06 18:49:51，"shangsu" ***@***.***> 写道：

我也有这个想法

**Comment by retr0reg** [comment]
Complete!
