### ISSUE TITLE
Environment Problem

### ISSUE THREAD

**Issue by WANG-Jiacheng** [DDizzzy79/Ret2GPT#4]
Hi, I think your work is very well but I encountered many related dependency issues while replicating your project, and I think these dependency issues seem difficult to solve on different platforms. I humbly request that you may provide a Docker image to assist in reproduction?

**Comment by retr0reg** [comment]
Its will be a great idea, working on that now

**Comment by retr0reg** [comment]
I recently updated the project on [pypi](https://pypi.org/project/Ret2GPT/) Hope it help bit!

**Comment by WANG-Jiacheng** [comment]
> I recently updated the project on [pypi](https://pypi.org/project/Ret2GPT/) Hope it help bit!

Thank you very much! It's so kind of you.
