### ISSUE TITLE
pip install chromadb --no-cache-dir

### ISSUE THREAD

**Issue by 3186447858** [DDizzzy79/Ret2GPT#6]
pip install chromadb --no-cache-dir
pip install tiktoken --no-cache-dir
安装完这两个依赖后 降低一下urllib3的版本 再配置一下终端的代理 就可以使用了

_Originally posted by @hjhjbmy in https://github.com/DDizzzy79/Ret2GPT/issues/1#issuecomment-1513195968_

**Comment by 3186447858** [comment]
network， 请问大师怎么配置代理？我的一直报<urllib3.connection.HTTPSConnection object at  0x7ff474675810>: Failed to establish a new connection: [Errno 101] Network is     unreachable')).

**Comment by 3186447858** [comment]
![360截图20230724185652612](https://github.com/DDizzzy79/Ret2GPT/assets/139957734/5109352e-2a67-4ec9-8537-2c74b351c2b1)
安装好了后，出现如图的问题。

**Comment by retr0reg** [comment]
可能要使用 `export` 命令来指定你的本地代理端口，比如说我的在7890端口 那就是`export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890`

**Comment by 3186447858** [comment]
请问大师。7890端口如何判断？

**Comment by 3186447858** [comment]
> 大师，本地代理ip和端口怎么获取呢？

**Comment by 3186447858** [comment]
请问国内要运行openai时不要设置国外的代理？

**Comment by BarnabyAlexandraBaron** [comment]
话说搭建的python的版本有推荐吗？有搭建好的python版本推荐吗？

**Comment by Savoir007** [comment]
d大佬 安装中遇到
![image](https://github.com/retr0reg/ChatWithBinary/assets/39297554/ab15e68d-06c0-4d65-8363-f5959f80d35c)
同时 open_key_ api 这个自定义baseurl吗 因为openai 个人apikey 老被封  在代码可以调整吗
